#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

exec 1>/tmp/metalware-default-output 2>&1

/bin/bash /var/lib/metalware/rendered/local/main/main.sh

mkdir <%= local.build_complete_path %>
touch <%= local.build_complete_path %>
