
cluster: testcluster
iptail: <%= alces.index + 100 %>
disk: vda
# GENERATE with `openssl passwd -1 $PASSWD`.
# This is 'password'.
encrypted_root_password: '$1$ljsJHJMq$aUpshtR7MKh3IjrFIUK9.1'
localmirror: false
yum_template: "<% if localmirror %>yum.local<% else %>yum.upstream<% end %>"
profile: MASTER
ssh_key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDhXUXuIDUG9BRva+m0BNSWg/E8OS7A153B1k0fUkSr2SNTUDRBIYNJ4XaX6l8HJNziugEeD2qhSX+qZT3jwr9t4tBcMh8hae72HXMaGPSQOFodNNAzaSAw8e5WYAbZAJnTMItrBkUO989ztwsAyfoeULxdW4ZRCpTECaqz1zklTEJxyUYwqJ3ar4n1cDdYsgXUldH2yopVSMx+EkH/NkQsg5GAqFJvP1yVvvhYgXBHF2tIA3iDWSU6HskAJpEIMjC0mxAWD0Gb3vNpPkp+1HbBPX1yp048EG4SF+jaLeJOrJqmMzngNuBJaUcNtP6UtsnCF7AVuCN1hAJxp1HKkY/v root@localhost.localdomain'

# Generic networking properties.
domain: <%= cluster %>.cluster.local
search_domains: "prv.<%= domain %> mgt.<%= domain %> ib.<%= domain %> <%= domain %>"
externaldns: 10.101.0.1
internaldns: <%= alces.hostip %>

# Properties for specific networks.
networks:
  prv:
    interface: em1
    hostname: "<%= alces.nodename %>.prv.<%= domain %>"
    short_hostname: "<%= alces.nodename %>.prv"
    ip: "10.10.0.<%= iptail %>"
    netmask: 255.255.0.0
    network: 10.10.0.0
    gateway: 10.10.0.11
    type:
    primary: true

  mgt:
    interface: em2
    hostname: "<%= alces.nodename %>.mgt.<%= domain %>"
    short_hostname: "<%= alces.nodename %>.mgt"
    ip: "10.11.0.<%= iptail %>"
    netmask: 255.255.0.0
    network: 10.11.0.0
    gateway:
    type:
    slave_interfaces: 'em3'

  ib:
    interface: ib0
    hostname: "<%= alces.nodename %>.ib.<%= domain %>"
    short_hostname: "<%= alces.nodename %>.ib"
    ip: "10.12.0.<%= iptail %>"
    netmask: 255.255.0.0
    network: 10.12.0.0
    gateway:
    type:

bond0_options: 'mode=1 primary=p3p2 miimon=80'
bond0_interfaces: 'em1 em2 p3p2' # XXX Needed?

# BMC defined separately as different to other networks.
bmcdomain: "<%= 'bmc.' + domain %>"
bmcip:
bmcnetmask: 255.255.248.0
bmcnetwork: 172.16.139.0
bmcgateway: 0.0.0.0
bmcpassword: 'Scitjaf4'
bmcchannel: 1
bmcuser: 2

files:
  main:
    - main.sh
  core:
    - core/base.sh
    - core/network-base.sh
    - core/network-ipmi.sh
    - core/network-join.sh
    - core/networking.sh
    - core/configs/yum.local
    - core/configs/yum.upstream
    - core/configs/authorized_keys
    - core/configs/ntp

  scripts:
    - local-script.sh
    - https://raw.githubusercontent.com/alces-software/metalware-default/bob/files/remote-script.sh
    - non-existent-local-script.sh
    - http://example.com/non-existent-remote-script.sh
  configs:
    - demo-config.conf
