
cluster: '<%= answer.cluster_name %>'
# GENERATE with `openssl passwd -1 $PASSWD`.
# XXX Change this so admin enters plain text root password, and we generate
# encrypted password here?
encrypted_root_password: '<%= answer.root_password %>'
profile: MASTER
ssh_key: '<%= answer.root_ssh_key %>'

# Generic networking properties.
domain: <%= answer.domain %>
search_domains: "<% config.networks.each do |network, details| -%><%= details.domain %>.<%= config.domain %> <% end -%><%= config.domain %>"
dns_type: "<%= answer.dns_type %>"
externaldns: <%= answer.externaldns %>
internaldns: <%= answer.internaldns %>
kernelappendoptions: ""
jobid: ""

# Properties for specific config.networks.
networks:
  pri:
    defined: <%= answer.pri_network_defined %>
    interface: "<%= answer.pri_network_interface %>"
    hostname: "<%= config.networks.pri.short_hostname %>.<%= config.domain %>"
    domain: "<%= answer.pri_network_domain %>"
    short_hostname: "<%= node.name %>.<%= config.networks.pri.domain %>"
    ip: "<%= answer.pri_network_ip %>"
    netmask: "<%= answer.pri_network_netmask %>"
    network: "<%= answer.pri_network_network %>"
    gateway: "<%= answer.pri_network_gateway %>"
    type:
    primary: true
    named_fwd_zone: "<%= config.networks.pri.domain %>.<%= config.domain %>"
    named_rev_zone: <% split_net = answer.pri_network_network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>
    firewallpolicy: internal

  mgt:
    defined: <%= answer.mgt_network_defined %>
    interface: "<%= answer.mgt_network_interface %>"
    hostname: "<%= config.networks.mgt.short_hostname %>.<%= config.domain %>"
    domain: "<%= answer.mgt_network_domain %>"
    short_hostname: "<%= node.name %>.<%= config.networks.mgt.domain %>"
    ip: "<%= answer.mgt_network_ip %>"
    netmask: "<%= answer.mgt_network_netmask %>"
    network: "<%= answer.mgt_network_network %>"
    gateway:
    type:
    named_fwd_zone: "<%= config.networks.mgt.domain %>.<%= config.domain %>"
    named_rev_zone: <% split_net = answer.mgt_network_network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>
    firewallpolicy: internal

  ib:
    defined: <%= answer.ib_network_defined %>
    interface: "<%= answer.ib_network_interface %>"
    hostname: "<%= config.networks.ib.short_hostname %>.<%= config.domain %>"
    domain: "<%= answer.ib_network_domain %>"
    short_hostname: "<%= node.name %>.<%= config.networks.ib.domain %>"
    ip: "<%= answer.ib_network_ip %>"
    netmask: "<%= answer.ib_network_netmask %>"
    network: "<%= answer.ib_network_network %>"
    gateway:
    type:
    named_fwd_zone: "<%= config.networks.ib.domain %>.<%= config.domain %>"
    named_rev_zone: <% split_net = answer.ib_network_network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>
    firewallpolicy: internal

  bmc:
    defined: <%= answer.bmc_network_defined %>
    interface: bmc
    hostname: "<%= config.networks.bmc.short_hostname %>.<%= config.networks.mgt.domain %>.<%= config.domain %>"
    domain: 'bmc'
    short_hostname: "<%= node.name %>.<%= config.networks.bmc.domain %>"
    ip: "<%= answer.bmc_network_ip %>"
    netmask: "<%= answer.mgt_network_netmask %>"
    network: "<%= answer.mgt_network_network %>"
    gateway: 0.0.0.0
    bmcpassword: "<%= answer.bmc_password %>"
    bmcchannel: 1
    bmcuser: 2
    bmcvlan: <%= answer.bmc_network_vlan %>
    firewallpolicy: management

disksetup: |
  zerombr
  bootloader --location=mbr --driveorder=sda --append="$bootloaderappend"
  clearpart --all --initlabel

  #Disk partitioning information
  part /boot --fstype ext4 --size=4096 --asprimary --ondisk sda
  part pv.01 --size=1 --grow --asprimary --ondisk sda
  volgroup system pv.01
  logvol  /  --fstype ext4 --vgname=system  --size=16384 --name=root
  logvol  /var --fstype ext4 --vgname=system --size=16384 --name=var
  logvol  /tmp --fstype ext4 --vgname=system --size=1 --grow --name=tmp
  logvol  swap  --fstype swap --vgname=system  --size=8096  --name=swap1

#disksetup: |
#  zerombr
#
#  bootloader --location=mbr --driveorder=sda --append="$bootloaderappend"
#  clearpart --all --initlabel
#
#  #Disk partitioning information
#  part /boot --fstype ext4 --size=1024 --asprimary --ondisk sda
#  part /boot2 --fstype ext4 --size=1024 --asprimary --ondisk sdb
#
#  part raid.01 --size 60000 --ondisk sda --asprimary
#  part raid.02 --size 60000 --ondisk sdb --asprimary
#
#  raid pv.01 --level=1 --fstype=ext4 --device=md0 raid.01 raid.02
#  volgroup system pv.01
#  logvol  /  --fstype ext4 --vgname=system  --size=1  --name=root --grow
#  logvol  /var  --fstype ext4 --vgname=system  --size=16384  --name=var
#  logvol  swap  --fstype swap --vgname=system  --size=16384  --name=swap1
#
#  part raid.03 --size=1 --ondisk sda --asprimary --grow
#  part raid.04 --size=1 --ondisk sdb --asprimary --grow
#
#  raid /tmp --fstype ext4 --fstype=ext4 --device=md1 --level=0 raid.03 raid.04

bond0_options: 'mode=1 primary=p3p2 miimon=80'
bond0_interfaces: 'em1 em2 p3p2' # XXX Needed?

templates:
  kickstart: <%= answer.kickstart_template %>
  pxelinux: <%= answer.pxelinux_template %>

files:
  platform:
    - /opt/alces/install/scripts/aws.sh
  main:
    - main.sh
  setup:
    - local-script.sh
  core:
    - core/base.sh
    - core/network-base.sh
    - core/network-ipmi.sh
    - core/network-join.sh
    - core/networking.sh
    - core/configs/authorized_keys
    - core/configs/ntp
  scripts:
    - local-script.sh

ntp:
  is_server: false
  server: controller.<%= config.networks.pri.domain %>.<%= config.domain %>

rsyslog:
  is_server: false
  server: controller

firewall:
  enabled: true
  internal:
    services: 'ssh http dhcp dns https mountd nfs ntp rpc-bind smtp syslog tftp tftp-client'
  external:
    services: 'ssh'
  management:
    services: 'ssh snmp'

repoconfig:
  # Repostiroy URL for kickstart builds 
  build_url: http://mirror.ox.ac.uk/sites/mirror.centos.org/7/os/x86_64/
  # If true, this server will host a client config file for the network
  is_server: false
  # Repoman source files for repository mirror server to use (comma separate)
  source_repos: base.upstream
  # The file for clients to curl containing repository information [OPTIONAL]
  # clientrepofile: http://myrepo.com/repo/client.repo
  clientrepofile: false
postfix:
  relayhost: "<%= answer.postfix_relay %>"
