
cluster: '<%= alces.answers.cluster_name %>'
# GENERATE with `openssl passwd -1 $PASSWD`.
# XXX Change this so admin enters plain text root password, and we generate
# encrypted password here?
encrypted_root_password: '<%= alces.answers.root_password %>'
profile: MASTER
ssh_key: '<%= alces.answers.root_ssh_key %>'

# Generic networking properties.
domain: <%= alces.answers.domain %>
search_domains: "<%= networks.pri.domain %>.<%= domain %> <%= networks.mgt.domain %>.<%= domain %> <%= networks.ib.domain %>.<%= domain %> <%= domain %>"
dns_type: "<%= alces.answers.dns_type %>"
externaldns: 10.101.0.1
internaldns: <%= alces.hostip %>
kernelappendoptions: ""
jobid: ""

# Properties for specific networks.
networks:
  pri:
    defined: <%= alces.answers.pri_network_defined %>
    interface: "<%= alces.answers.pri_network_interface %>"
    hostname: "<%= networks.pri.short_hostname %>.<%= domain %>"
    domain: "<%= alces.answers.pri_network_domain %>"
    short_hostname: "<%= alces.nodename %>.<%= networks.pri.domain %>"
    ip: "<%= alces.answers.pri_network_ip %>"
    netmask: "<%= alces.answers.pri_network_netmask %>"
    network: "<%= alces.answers.pri_network_network %>"
    gateway:
    type:
    primary: true
    named_fwd_zone: "<%= networks.pri.domain %>.<%= domain %>"
    named_rev_zone: <% split_net = networks.pri.network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>

  mgt:
    defined: <%= alces.answers.mgt_network_defined %>
    interface: "<%= alces.answers.mgt_network_interface %>"
    hostname: "<%= networks.mgt.short_hostname %>.<%= domain %>"
    domain: "<%= alces.answers.mgt_network_domain %>"
    short_hostname: "<%= alces.nodename %>.<%= networks.mgt.domain %>"
    ip: "<%= alces.answers.mgt_network_ip %>"
    netmask: "<%= alces.answers.mgt_network_netmask %>"
    network: "<%= alces.answers.mgt_network_network %>"
    gateway:
    type:
    named_fwd_zone: "<%= networks.mgt.domain %>.<%= domain %>"
    named_rev_zone: <% split_net = networks.mgt.network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>

  ib:
    defined: <%= alces.answers.ib_network_defined %>
    interface: "<%= alces.answers.ib_network_interface %>"
    hostname: "<%= networks.ib.short_hostname %>.<%= domain %>"
    domain: "<%= alces.answers.ib_network_domain %>"
    short_hostname: "<%= alces.nodename %>.<%= networks.ib.domain %>"
    ip: "<%= alces.answers.ib_network_ip %>"
    netmask: "<%= alces.answers.ib_network_netmask %>"
    network: "<%= alces.answers.ib_network_network %>"
    gateway:
    type:
    named_fwd_zone: "<%= networks.ib.domain %>.<%= domain %>"
    named_rev_zone: <% split_net = networks.ib.network.split(/\./) -%><%= split_net[1] %>.<%= split_net[0] %>

  bmc:
    defined: <%= alces.answers.bmc_network_defined %>
    interface: bmc
    hostname: "<%= alces.nodename %>.bmc.<%= networks.mgt.domain %>.<%= domain %>"
    short_hostname: "<%= alces.nodename %>.bmc"
    ip: "<%= alces.answers.bmc_network_ip %>"
    netmask: "<%= alces.answers.mgt_network_netmask %>"
    network: "<%= alces.answers.mgt_network_network %>"
    gateway: 0.0.0.0
    bmcpassword: "<%= alces.answers.bmc_password %>"
    bmcchannel: 1
    bmcuser: 2
    named_fwd_zone: "<%= networks.bmc.domain %>.<%= domain %>"

disksetup: |
  zerombr
  bootloader --location=mbr --driveorder=sda --append="$bootloaderappend"
  clearpart --all --initlabel

  #Disk partitioning information
  part /boot --fstype ext4 --size=4096 --asprimary --ondisk sda
  part pv.01 --size=1 --grow --asprimary --ondisk sda
  volgroup system pv.01
  logvol  /  --fstype ext4 --vgname=system  --size=16384 --name=root
  logvol  /var --fstype ext4 --vgname=system --size=16384 --name=var
  logvol  /tmp --fstype ext4 --vgname=system --size=1 --grow --name=tmp
  logvol  swap  --fstype swap --vgname=system  --size=8096  --name=swap1

#disksetup: |
#  zerombr
#
#  bootloader --location=mbr --driveorder=sda --append="$bootloaderappend"
#  clearpart --all --initlabel
#
#  #Disk partitioning information
#  part /boot --fstype ext4 --size=1024 --asprimary --ondisk sda
#  part /boot2 --fstype ext4 --size=1024 --asprimary --ondisk sdb
#
#  part raid.01 --size 60000 --ondisk sda --asprimary
#  part raid.02 --size 60000 --ondisk sdb --asprimary
#
#  raid pv.01 --level=1 --fstype=ext4 --device=md0 raid.01 raid.02
#  volgroup system pv.01
#  logvol  /  --fstype ext4 --vgname=system  --size=1  --name=root --grow
#  logvol  /var  --fstype ext4 --vgname=system  --size=16384  --name=var
#  logvol  swap  --fstype swap --vgname=system  --size=16384  --name=swap1
#
#  part raid.03 --size=1 --ondisk sda --asprimary --grow
#  part raid.04 --size=1 --ondisk sdb --asprimary --grow
#
#  raid /tmp --fstype ext4 --fstype=ext4 --device=md1 --level=0 raid.03 raid.04

bond0_options: 'mode=1 primary=p3p2 miimon=80'
bond0_interfaces: 'em1 em2 p3p2' # XXX Needed?

templates:
  kickstart: <%= alces.answers.kickstart_template %>
  pxelinux: <%= alces.answers.pxelinux_template %>

files:
  platform:
    - /opt/alces/install/scripts/aws.sh
  main:
    - main.sh
  setup:
    - local-script.sh
    - https://raw.githubusercontent.com/alces-software/metalware-default/master/files/remote-script.sh
    - non-existent-local-script.sh
    - http://example.com/non-existent-remote-script.sh
  core:
    - core/base.sh
    - core/network-base.sh
    - core/network-ipmi.sh
    - core/network-join.sh
    - core/networking.sh
    - core/configs/authorized_keys
    - core/configs/ntp
  scripts:
    - local-script.sh
    - https://raw.githubusercontent.com/alces-software/metalware-default/master/files/remote-script.sh
    - non-existent-local-script.sh
    - http://example.com/non-existent-remote-script.sh
