networks:
  pri:
    defined: <%= alces.answers.pri_network_defined %>
    ip: <%= alces.answers.pri_network_ip %>
    short_hostname: <%= alces.answers.pri_network_short_hostname %>
    interface: <%= alces.answers.pri_network_interface %>
  mgt:
    defined: <%= alces.answers.mgt_network_defined %>
    ip: <%= alces.answers.mgt_network_ip %>
    interface: <%= alces.answers.mgt_network_interface %>
  bmc:
    defined: <%= alces.answers.bmc_network_defined %>
    ip: <%= alces.answers.bmc_network_ip %>
    interface: <%= alces.answers.bmc_network_interface %>
  ib:
    defined: <%= alces.answers.ib_network_defined %>
    ip: <%= alces.answers.ib_network_ip %>
    interface: <%= alces.answers.ib_network_interface %>
  ext:
    defined: <%= alces.answers.ext_network_defined %>
    domain: <%= alces.answers.ext_network_domain %>
    ip: <%= alces.answers.ext_network_ip %>
    network: <%= alces.answers.ext_network_network %>
    netmask: <%= alces.answers.ext_network_netmask %>
    interface: <%= alces.answers.ext_network_interface %>
    firewallpolicy: external
build_method: self
files:
  setup:
    - setup/xinetd.sh
    - setup/dhcp.sh
    - setup/http.sh
    - setup/repo.sh
  main:
    - setup/main.sh
  core:
    - core/network-base.sh
    - core/network-ipmi.sh
    - core/network-join.sh
    - core/networking.sh
    - core/configs/authorized_keys
build:
  pxeboot_path: /var/lib/tftpboot/boot
ntp:
  is_server: true
