networks:
  pri:
    defined: <%= alces.answers.pri_network_defined %>
    ip: <%= alces.answers.pri_network_ip %>
    short_hostname: <%= alces.answers.pri_network_short_hostname %>
  mgt:
    defined: <%= alces.answers.mgt_network_defined %>
  bmc:
    defined: <%= alces.answers.bmc_network_defined %>
  ib:
    defined: <%= alces.answers.ib_network_defined %>
build_method: self
files:
  setup:
    - setup/xinetd.sh
    - setup/dhcp.sh
    - setup/http.sh
    - setup/repo.sh
  main:
    - setup/main.sh
  core:
    - core/network-base.sh
    - core/network-ipmi.sh
    - core/network-join.sh
    - core/networking.sh
    - core/configs/authorized_keys
build:
  pxeboot_path: /var/lib/tftpboot/boot
ntp:
  is_server: true
